#!/bin/bash
set -e

echo "Formatting code with ktfmt…"

# Run ktfmt formatter using Gradle
if ! ./gradlew --quiet --no-daemon ktfmtFormat; then
    echo "Formatting with ktfmt failed"
    exit 1
fi

# Get list of staged Kotlin files
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.kt$|\.kts$' || true)
if [ ! -z "$staged_files" ]; then
    git add $staged_files
fi

echo "Formatting completed."
exit 0