/* WARNING! All changes made to this file will be lost! */

#ifndef W_DEFAULT_CONFIG_H_WAF
#define W_DEFAULT_CONFIG_H_WAF

#define SRCDIR "/home/rohit/Projects/proot/talloc"
#define HAVE_SYS_UTSNAME_H 1
#define SYSTEM_UNAME_SYSNAME "Linux"
#define SYSTEM_UNAME_MACHINE "dontcare"
#define SYSTEM_UNAME_RELEASE "dontcare"
#define SYSTEM_UNAME_VERSION "dontcare"
#define HAVE_STDIO_H 1
#define HAVE_SIMPLE_C_PROG 1
#define HAVE_VISIBILITY_ATTR 1
#define HAVE_CONSTRUCTOR_ATTRIBUTE 1
#define HAVE_DESTRUCTOR_ATTRIBUTE 1
#define HAVE___ATTRIBUTE__ 1
#define INLINE_MACRO 1
#define _GNU_SOURCE 1
#define _XOPEN_SOURCE_EXTENDED 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STDDEF_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_CTYPE_H 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDARG_H 1
#define HAVE_LIMITS_H 1
#define HAVE_ASSERT_H 1
#define WORKING_GETCONF_LFS_CFLAGS 1
#define HAVE_LARGEFILE 1
#define STDC_HEADERS 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H 1
#define TIME_WITH_SYS_TIME 1
#define SHLIBEXT "so"
#define HAVE_ENDIAN_H 1
#define HAVE_SYS_ENDIAN_H 1
#define HAVE_LITTLE_ENDIAN 1
/* #undef HAVE_BIG_ENDIAN */
#define HAVE_SIGNAL_H 1
/* #undef RETSIGTYPE_INT */
#define RETSIGTYPE void
#define HAVE_FUNCTION_MACRO 1
#define HAVE_VA_COPY 1
#define LINUX 1
#define BOOL_DEFINED 1
#define HAVE_LIBREPLACE 1
#define LIBREPLACE_NETWORK_CHECKS 1
#define HAVE_LINUX_TYPES_H 1
#define HAVE_LOCALE_H 1
#define HAVE_FCNTL_H 1
#define HAVE_FNMATCH_H 1
#define HAVE_GLOB_H 1
#define HAVE_LANGINFO_H 1
#define HAVE_PWD_H 1
#define HAVE_SYS_CAPABILITY_H 1
#define HAVE_SYS_EPOLL_H 1
#define HAVE_SYS_FCNTL_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_SYS_MMAN_H 1
#define HAVE_SYS_RESOURCE_H 1
#define HAVE_SYS_SHM_H 1
#define HAVE_SYS_STATFS_H 1
#define HAVE_SYS_STATVFS_H 1
#define HAVE_SYS_VFS_H 1
#define HAVE_SYS_XATTR_H 1
#define HAVE_TERMIO_H 1
#define HAVE_TERMIOS_H 1
#define HAVE_SYS_FILE_H 1
#define HAVE_SYS_UCONTEXT_H 1
#define HAVE_SYS_WAIT_H 1
#define HAVE_DECL_MALLOC 1
#define HAVE_GRP_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SETJMP_H 1
#define HAVE_UTIME_H 1
#define HAVE_SYS_SYSLOG_H 1
#define HAVE_SYSLOG_H 1
#define HAVE_SYS_MOUNT_H 1
#define HAVE_MNTENT_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_NETDB_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_NETINET_IN_SYSTM_H 1
#define HAVE_NETINET_IP_H 1
#define HAVE_NETINET_TCP_H 1
#define HAVE_SYS_UN_H 1
#define HAVE_SYS_UIO_H 1
#define HAVE_IFADDRS_H 1
#define HAVE_DIRENT_H 1
#define HAVE_ERRNO_H 1
#define HAVE_GETOPT_H 1
#define HAVE_ICONV_H 1
#define HAVE_LINUX_OPENAT2_H 1
#define HAVE_SYS_INOTIFY_H 1
#define HAVE_INOTIFY_INIT 1
#define HAVE_ZLIB_H 1
#define HAVE_ASM_UNISTD_H 1
#define HAVE_SYS_UNISTD_H 1
#define HAVE_ALLOCA_H 1
#define HAVE_FLOAT_H 1
/* #undef HAVE_RPC_RPC_HEADERS */
#define HAVE_TIRPC 1
#define HAVE_RPC_RPC_H 1
#define HAVE_RPC_NETTYPE_H 1
/* #undef HAVE_SYS_SYSCTL_H */
#define HAVE_SYS_SYSMACROS_H 1
#define HAVE_SYS_CDEFS_H 1
#define HAVE_UTMP_H 1
#define HAVE_UTMPX_H 1
#define HAVE_LASTLOG_H 1
#define HAVE_SYSCALL_H 1
#define HAVE_SYS_SYSCALL_H 1
#define HAVE_STDATOMIC_H 1
#define HAVE_LIBGEN_H 1
#define HAVE_WNO_FORMAT_TRUNCATION "1"
#define HAVE_WNO_UNUSED_FUNCTION "1"
#define HAVE_WNO_STRICT_OVERFLOW "1"
#define HAVE_WNO_UNUSED_BUT_SET_VARIABLE "1"
#define HAVE_SYS_PRCTL_H 1
#define HAVE_PRCTL 1
#define HAVE_OPEN_O_DIRECT 1
#define HAVE_LONG_LONG 1
#define HAVE_INTPTR_T 1
#define HAVE_UINTPTR_T 1
#define HAVE_PTRDIFF_T 1
/* #undef HAVE_COMPARISON_FN_T */
#define HAVE_BOOL 1
#define HAVE_INT8_T 1
#define HAVE_UINT8_T 1
#define HAVE_INT16_T 1
#define HAVE_UINT16_T 1
#define HAVE_INT32_T 1
#define HAVE_UINT32_T 1
#define HAVE_INT64_T 1
#define HAVE_UINT64_T 1
#define HAVE_SIZE_T 1
#define HAVE_SSIZE_T 1
#define HAVE_INO_T 1
#define HAVE_LOFF_T 1
/* #undef HAVE_OFFSET_T */
#define offset_t loff_t
#define HAVE_VOLATILE 1
#define HAVE_UINT_T 1
#define HAVE_BLKSIZE_T 1
#define HAVE_BLKCNT_T 1
#define SIZEOF_BOOL 1
#define SIZEOF_CHAR 1
#define SIZEOF_INT 4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_LONG 8
#define SIZEOF_SHORT 2
#define SIZEOF_SIZE_T 8
#define SIZEOF_SSIZE_T 8
#define SIZEOF_INT8_T 1
#define SIZEOF_UINT8_T 1
#define SIZEOF_INT16_T 2
#define SIZEOF_UINT16_T 2
#define SIZEOF_INT32_T 4
#define SIZEOF_UINT32_T 4
#define SIZEOF_INT64_T 8
#define SIZEOF_UINT64_T 8
#define SIZEOF_VOID_P 8
#define SIZEOF_OFF_T 8
#define SIZEOF_DEV_T 8
#define SIZEOF_INO_T 8
#define SIZEOF_TIME_T 8
#define HAVE_SOCKLEN_T 1
#define HAVE_STRUCT_IFADDRS 1
#define HAVE_STRUCT_ADDRINFO 1
#define HAVE_STRUCT_SOCKADDR 1
#define HAVE_STRUCT_SOCKADDR_IN6 1
#define HAVE_STRUCT_SOCKADDR_STORAGE 1
#define HAVE_SA_FAMILY_T 1
#define HAVE_SIG_ATOMIC_T_TYPE 1
#define HAVE_SIGSETMASK 1
/* #undef HAVE_SIGGETMASK */
#define HAVE_SIGPROCMASK 1
#define HAVE_SIGBLOCK 1
#define HAVE_SIGACTION 1
/* #undef HAVE_SIGSET */
#define HAVE_INET_NTOA 1
#define HAVE_INET_ATON 1
#define HAVE_INET_NTOP 1
#define HAVE_INET_PTON 1
#define HAVE_CONNECT 1
#define HAVE_GETHOSTBYNAME 1
#define HAVE_GETADDRINFO 1
#define HAVE_GETNAMEINFO 1
#define HAVE_FREEADDRINFO 1
#define HAVE_GAI_STRERROR 1
#define HAVE_SOCKETPAIR 1
/* #undef HAVE_MEMSET_S */
/* #undef HAVE_MEMSET_EXPLICIT */
#define HAVE_GCC_VOLATILE_MEMORY_PROTECTION 1
#define HAVE_IPV6_V6ONLY 1
#define HAVE_NET_IF_H 1
#define HAVE_IPV6 1
#define HAVE_UCONTEXT_T 1
#define HAVE___SYNC_FETCH_AND_ADD 1
#define HAVE___SYNC_ADD_AND_FETCH 1
/* #undef HAVE_ATOMIC_ADD_32 */
#define HAVE___ATOMIC_ADD_FETCH 1
#define HAVE___ATOMIC_ADD_LOAD 1
#define HAVE_ATOMIC_THREAD_FENCE 1
#define HAVE_ATOMIC_THREAD_FENCE_SUPPORT 1
#define HAVE_FALLTHROUGH_ATTRIBUTE 1
#define HAVE_STRDUP 1
#define HAVE_MEMMEM 1
#define HAVE_PRINTF 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_STRCPY 1
#define HAVE_STRNCPY 1
/* #undef HAVE_SHL_LOAD */
/* #undef HAVE_SHL_UNLOAD */
/* #undef HAVE_SHL_FINDSYM */
#define HAVE_PIPE 1
#define HAVE_STRFTIME 1
#define HAVE_SRANDOM 1
#define HAVE_RANDOM 1
#define HAVE_SRAND 1
#define HAVE_RAND 1
#define HAVE_USLEEP 1
#define HAVE_SETBUFFER 1
#define HAVE_LSTAT 1
#define HAVE_GETPGRP 1
#define HAVE_UTIME 1
#define HAVE_UTIMES 1
#define HAVE_SETUID 1
#define HAVE_SETEUID 1
#define HAVE_SETREUID 1
#define HAVE_SETRESUID 1
#define HAVE_SETGID 1
#define HAVE_SETEGID 1
#define HAVE_SETREGID 1
#define HAVE_SETRESGID 1
#define HAVE_CHROOT 1
#define HAVE_STRERROR 1
#define HAVE_VSYSLOG 1
#define HAVE_SETLINEBUF 1
#define HAVE_MKTIME 1
#define HAVE_FTRUNCATE 1
/* #undef HAVE_CHSIZE */
#define HAVE_RENAME 1
#define HAVE_WAITPID 1
#define HAVE_WAIT4 1
#define HAVE_INITGROUPS 1
#define HAVE_PREAD 1
#define HAVE_PWRITE 1
#define HAVE_STRNDUP 1
#define HAVE_STRCASESTR 1
#define HAVE_STRSEP 1
#define HAVE_STRTOK_R 1
#define HAVE_MKDTEMP 1
#define HAVE_DUP2 1
#define HAVE_DPRINTF 1
#define HAVE_VDPRINTF 1
#define HAVE_ISATTY 1
#define HAVE_CHOWN 1
#define HAVE_LCHOWN 1
#define HAVE_LINK 1
#define HAVE_READLINK 1
#define HAVE_SYMLINK 1
#define HAVE_REALPATH 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define HAVE_ASPRINTF 1
#define HAVE_VASPRINTF 1
#define HAVE_SETENV 1
#define HAVE_UNSETENV 1
#define HAVE_STRNLEN 1
#define HAVE_STRTOULL 1
/* #undef HAVE___STRTOULL */
/* #undef HAVE_STRTOUQ */
#define HAVE_STRTOLL 1
/* #undef HAVE___STRTOLL */
/* #undef HAVE_STRTOQ */
#define HAVE_MEMALIGN 1
#define HAVE_POSIX_MEMALIGN 1
#define HAVE_FMEMOPEN 1
/* #undef HAVE_RENAMEAT2 */
#define HAVE_MALLOC_H 1
#define HAVE_DECL_MEMALIGN 1
#define _POSIX_FALLOCATE_CAPABLE_LIBC 1
#define HAVE_POSIX_FALLOCATE 1
#define HAVE_DIRNAME 1
#define HAVE_BASENAME 1
#define HAVE_STRLCPY 1
#define HAVE_STRLCAT 1
/* #undef HAVE_GETPEEREID */
/* #undef HAVE_SETPROCTITLE */
/* #undef HAVE_SETPROCTITLE_INIT */
/* #undef HAVE_CLOSEFROM */
#define HAVE_PEERCRED 1
#define HAVE_BSD_STRTOLL 1
#define HAVE_IF_NAMEINDEX 1
#define HAVE_IF_NAMETOINDEX 1
#define HAVE_STRERROR_R 1
#define HAVE_SYSLOG 1
/* #undef HAVE_GET_CURRENT_DIR_NAME */
#define HAVE_TIMEGM 1
#define HAVE_GETIFADDRS 1
#define HAVE_FREEIFADDRS 1
#define HAVE_MMAP 1
#define HAVE_SETGROUPS 1
#define HAVE_SYSCALL 1
#define HAVE_SETSID 1
/* #undef HAVE_GETGRENT_R */
#define HAVE_GETGRGID_R 1
#define HAVE_GETGRNAM_R 1
#define HAVE_GETGROUPLIST 1
#define HAVE_GETPAGESIZE 1
/* #undef HAVE_GETPWENT_R */
#define HAVE_GETPWNAM_R 1
#define HAVE_GETPWUID_R 1
#define HAVE_EPOLL_CREATE1 1
#define HAVE_GETPROGNAME 1
/* #undef HAVE_COPY_FILE_RANGE */
#define HAVE_SYSCALL_COPY_FILE_RANGE 1
#define HAVE_XATTR_SUPPORT 1
#define HAVE_GETXATTR 1
#define HAVE_XATTR_XATTR 1
/* #undef XATTR_ADDITIONAL_OPTIONS */
#define HAVE_DLFCN_H 1
#define HAVE_DLOPEN 1
#define HAVE_DLSYM 1
#define HAVE_DLERROR 1
#define HAVE_DLCLOSE 1
#define HAVE_DECL_DLOPEN 1
/* #undef DLOPEN_TAKES_UNSIGNED_FLAGS */
#define HAVE_FDATASYNC 1
#define HAVE_DECL_FDATASYNC 1
#define HAVE_CLOCK_GETTIME 1
#define HAVE_CLOCK_MONOTONIC 1
#define HAVE_CLOCK_PROCESS_CPUTIME_ID 1
#define HAVE_CLOCK_REALTIME 1
#define HAVE_STRUCT_TIMESPEC 1
#define HAVE_ARPA_NAMESER_H 1
#define HAVE_RESOLV_H 1
#define HAVE_RES_SEARCH 1
/* #undef HAVE_DECL_DGETTEXT */
/* #undef HAVE_DECL_GETTEXT */
/* #undef HAVE_DECL_BINDTEXTDOMAIN */
/* #undef HAVE_DECL_TEXTDOMAIN */
/* #undef HAVE_DECL_BIND_TEXTDOMAIN_CODESET */
/* #undef HAVE_BINDTEXTDOMAIN */
/* #undef HAVE_TEXTDOMAIN */
/* #undef HAVE_BIND_TEXTDOMAIN_CODESET */
/* #undef HAVE_DGETTEXT */
/* #undef HAVE_GETTEXT */
#define HAVE_PTHREAD_H 1
#define HAVE_PTHREAD_CREATE 1
#define HAVE_PTHREAD_ATTR_INIT 1
#define HAVE_PTHREAD 1
/* #undef HAVE_PTHREAD_MUTEXATTR_SETROBUST */
/* #undef HAVE_PTHREAD_MUTEXATTR_SETROBUST_NP */
/* #undef HAVE_DECL_PTHREAD_MUTEX_ROBUST */
/* #undef HAVE_DECL_PTHREAD_MUTEX_ROBUST_NP */
/* #undef HAVE_PTHREAD_MUTEX_CONSISTENT */
/* #undef HAVE_PTHREAD_MUTEX_CONSISTENT_NP */
#define HAVE___THREAD 1
/* #undef HAVE_CRYPT */
/* #undef HAVE_CRYPT_R */
/* #undef HAVE_CRYPT_RN */
#define HAVE_DECL_RL_EVENT_HOOK 0
/* #undef HAVE_PROGRAM_INVOCATION_SHORT_NAME */
#define HAVE_DECL_SNPRINTF 1
#define HAVE_DECL_VSNPRINTF 1
#define HAVE_DECL_ASPRINTF 1
#define HAVE_DECL_VASPRINTF 1
#define HAVE_ERRNO_DECL 1
#define HAVE_DECL_EWOULDBLOCK 1
#define HAVE_ENVIRON_DECL 1
/* #undef HAVE_GETGRENT_R_DECL */
/* #undef HAVE_GETPWENT_R_DECL */
#define HAVE_PREAD_DECL 1
#define HAVE_PWRITE_DECL 1
#define HAVE_SETENV_DECL 1
#define HAVE_SETRESGID_DECL 1
#define HAVE_SETRESUID_DECL 1
#define HAVE_EPOLL 1
#define HAVE_SYS_EVENTFD_H 1
#define HAVE_EVENTFD 1
#define HAVE_POLL_H 1
#define HAVE_POLL 1
#define HAVE_STRPTIME 1
#define HAVE_DECL_STRPTIME 1
#define HAVE_WORKING_STRPTIME 1
#define HAVE_DECL_GETTIMEOFDAY 1
#define HAVE_GETTIMEOFDAY_TZ 1
/* #undef HAVE_GETTIMEOFDAY_TZ_VOID */
#define HAVE_C99_VSNPRINTF 1
#define HAVE_SHARED_MMAP 1
#define HAVE_MREMAP 1
#define HAVE_INCOHERENT_MMAP 1
#define HAVE_IMMEDIATE_STRUCTURES 1
#define HAVE_MKDIR_MODE 1
#define HAVE_STRUCT_STAT_ST_RDEV 1
#define HAVE_ST_RDEV 1
#define HAVE_SS_FAMILY 1
/* #undef HAVE___SS_FAMILY */
/* #undef HAVE_SOCKADDR_SA_LEN */
/* #undef HAVE_SOCK_SIN_LEN */
/* #undef HAVE_SOCK_SIN6_LEN */
#define HAVE_UNIXSOCKET 1
#define HAVE_SECURE_MKSTEMP 1
/* #undef HAVE_IFACE_GETIFADDRS */
/* #undef HAVE_IFACE_AIX */
/* #undef HAVE_IFACE_IFCONF */
/* #undef HAVE_IFACE_IFREQ */
/* #undef HAVE_DECL_GETPWENT_R */
/* #undef HAVE_DECL_GETGRENT_R */
/* #undef STRERROR_R_XSI_NOT_GNU */
#define TALLOC_BUILD_VERSION_MAJOR 2
#define TALLOC_BUILD_VERSION_MINOR 4
#define TALLOC_BUILD_VERSION_RELEASE 3
#define HAVE_SYS_AUXV_H 1
#define HAVE_GETAUXVAL 1

#endif /* W_DEFAULT_CONFIG_H_WAF */
