package com.rk.ai.agent.tools

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.serialization.json.JsonObject

/**
 * Simple global store for suggestions generated by SuggestionTools.
 * UI components can collect from this flow to display live suggestions.
 */
object SuggestionStore {
    val suggestions = MutableStateFlow<List<JsonObject>>(emptyList())
    fun update(newSuggestions: List<JsonObject>) {
        suggestions.value = newSuggestions
    }
}
