package com.rk.xededitor.Settings

object Keys {
    const val LAST_OPENED_FILES="last_opened_files"
    const val PIN_LINE_NUMBER="pinline"
    const val WORD_WRAP_ENABLED="wordwrap"
    const val TAB_SIZE="tabsize"
    const val CURSOR_ANIMATION_ENABLED="CursorAnimation"
    const val TEXT_SIZE="textsize"
    const val LAST_OPENED_PATH="lastOpenedPath"
    const val USE_SPACE_INTABS="useSpaces"
    const val SHOW_ARROW_KEYS="show_arrows"
    const val OLED="isOled"
    const val DEFAULT_NIGHT_MODE="default_night_mode"
    const val ENABLE_PLUGINS="enablePlugin"
    const val SELECTED_THEME="selected_theme"
    const val PRIVATE_DATA="privateData"
    const val THEMES="Themes"
    const val KEEP_DRAWER_LOCKED="keepdrawerlocked"
    const val DIAGONAL_SCROLL="diagnolScroll"
    const val SHOW_LINE_NUMBERS="showlinenumbers"
    const val AUTO_SAVE="auto_save"
    const val AUTO_SAVE_TIME="auto_save_time"
    const val AUTO_SAVE_TIME_VALUE="auto_save_time_value"
    const val VERSION_CODE="version_code"
    const val PROJECTS="opened_projects"
    //used in SettingsMainActivity
    const val APPLICATION="app_"
    const val EDITOR="editor_"
    const val PLUGINS="plugins_"
}