package com.rk.settings

object PreferencesKeys {
    const val PIN_LINE_NUMBER = "pinline"
    const val WORD_WRAP_ENABLED = "wordwrap"
    const val TAB_SIZE = "tabsize"
    const val CURSOR_ANIMATION_ENABLED = "CursorAnimation"
    const val TEXT_SIZE = "textsize"
    const val SHOW_ARROW_KEYS = "show_arrows"
    const val OLED = "isOled"
    const val MONET = "isMonet"
    const val DEFAULT_NIGHT_MODE = "default_night_mode"
    const val KEEP_DRAWER_LOCKED = "keepdrawerlocked"
    const val DIAGONAL_SCROLL = "diagnolScroll"
    const val SHOW_LINE_NUMBERS = "showlinenumbers"
    const val AUTO_SAVE = "auto_save"
    const val AUTO_SAVE_TIME_VALUE = "auto_save_time_value"
    const val PROJECTS = "opened_projects"
    const val FAIL_SAFE = "failsafe"
    const val SHOW_SUGGESTIONS = "show_suggestions"
    const val CHECK_UPDATE="check_update"
    const val LAST_UPDATE_CHECK="last_update_check"
    const val USE_SORA_SEARCH="use_sora_search"
    const val WORD_WRAP_TXT="text_ww"
    const val ANTI_WORD_BREAKING="anti_word_breaking"
    const val TERMUX_EXEC="termux_exec"
    const val FONT_GSON="selected_font"
    const val SELECTED_FONT_PATH="selected_font_path"
    const val IS_SELECTED_FONT_ASSEST="is_font_asset"
    const val SELECTED_ENCODING="encoding"
    // todo encrypt git keys
    const val GIT_CRED = "git_cred"
    const val GIT_USER_DATA = "git_user_data"
    const val GIT_REPO_DIR = "git_repo_dir"
    const val VIEWPAGER_SMOOTH_SCROLL = "viewpager_smooth_scroll"
}
