package com.rk.settings

object PreferencesKeys {
    const val PIN_LINE_NUMBER = "pinline"
    const val WORD_WRAP_ENABLED = "wordwrap"
    const val TAB_SIZE = "tabsize"
    const val CURSOR_ANIMATION_ENABLED = "CursorAnimation"
    const val TEXT_SIZE = "textsize"
    const val SHOW_ARROW_KEYS = "show_arrows"
    const val OLED = "isOled"
    const val MONET = "isMonet"
    const val DEFAULT_NIGHT_MODE = "default_night_mode"
    const val KEEP_DRAWER_LOCKED = "keepdrawerlocked"
    const val DIAGONAL_SCROLL = "diagnolScroll"
    const val SHOW_LINE_NUMBERS = "showlinenumbers"
    const val AUTO_SAVE = "auto_save"
    const val AUTO_SAVE_TIME_VALUE = "auto_save_time_value"
    const val VERSION_CODE = "version_code"
    const val PROJECTS = "opened_projects"
    const val SHELL = "shell"
    const val FAIL_SAFE = "failsafe"
    const val LINK2SYMLINK = "link2symlink"
    const val ASHMEM_MEMFD = "ashmem_memfd"
    const val SYSVIPC = "sysvipc"
    const val KILL_ON_EXIT = "kill-on_exit"
    const val FORCE_CHAR = "force_char_in_terminal"
    const val CTRL_WORKAROUND = "ctrlworkaround"
    const val EDITOR_FONT = "editor_font"
    const val SHOW_SUGGESTIONS = "show_suggestions"
    const val SHOW_VIRTUAL_KEYBOARD = "show_virtual_keyboard"
    const val CHECK_UPDATE="check_update"
    const val LAST_UPDATE_CHECK="last_update_check"
    const val USE_SORA_SEARCH="use_sora_search"
    const val WORD_WRAP_TXT="text_ww"
    // todo encrypt git keys
    const val GIT_CRED = "git_cred"
    const val GIT_USER_DATA = "git_user_data"
    const val GIT_REPO_DIR = "git_repo_dir"
    const val TERMINAL_TEXT_SIZE = "terminal_text_size"
    const val VIEWPAGER_SMOOTH_SCROLL = "viewpager_smooth_scroll"
}
