@file:OptIn(ExperimentalUuidApi::class)
package com.rk.ai.nativeagent.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import com.rk.ai.nativeagent.engine.VibeCodingEngine
import com.rk.ai.models.UIMessagePart
import com.rk.ai.models.Tool
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Simple panel that shows a list of suggestions generated by the VibeCoding suggestion tools.
 * It expects the engine to expose a `suggestionsFlow` of type `MutableStateFlow<List<JsonObject>>`.
 */
@Composable
fun SuggestionPanel(
    engine: VibeCodingEngine,
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier,
) {
    val suggestions = engine.suggestionsFlow.collectAsState()
    Surface(
        modifier = modifier.fillMaxSize(),
        color = MaterialTheme.colorScheme.surfaceContainerLow,
    ) {
        Column(modifier = Modifier.fillMaxSize()) {
            Row(
                modifier = Modifier.fillMaxWidth().padding(8.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.SpaceBetween,
            ) {
                Text("Suggestions", style = MaterialTheme.typography.titleMedium)
                IconButton(onClick = onDismiss) { Icon(Icons.Outlined.Close, contentDescription = "Close") }
            }
            Divider()
            if (suggestions.value.isEmpty()) {
                Box(modifier = Modifier.fillMaxSize(), contentAlignment = Alignment.Center) {
                    Text("No suggestions available", style = MaterialTheme.typography.bodyMedium)
                }
            } else {
                LazyColumn(modifier = Modifier.weight(1f).padding(8.dp)) {
                    items(suggestions.value) { sug ->
                        SuggestionItem(suggestion = sug, engine = engine)
                    }
                }
            }
        }
    }
}

@Composable
private fun SuggestionItem(suggestion: JsonObject, engine: VibeCodingEngine) {
    val text = suggestion["text"]?.jsonPrimitive?.content ?: "<no text>"
    val confidence = suggestion["confidence"]?.jsonPrimitive?.floatOrNull ?: 0f
    val confidenceColor = when {
        confidence >= 0.8f -> Color(0xFF4CAF50) // green
        confidence >= 0.5f -> Color(0xFFFFC107) // amber
        else -> Color(0xFFF44336) // red
    }
    Card(
        modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
        shape = MaterialTheme.shapes.medium,
        elevation = CardDefaults.elevatedCardElevation(defaultElevation = 2.dp),
    ) {
        Row(
            modifier = Modifier.fillMaxWidth().padding(8.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.SpaceBetween,
        ) {
            Column(modifier = Modifier.weight(1f)) {
                Text(text, style = MaterialTheme.typography.bodyMedium)
                Spacer(Modifier.height(4.dp))
                Text("Confidence: ${"%.2f".format(confidence)}", style = MaterialTheme.typography.labelSmall, color = confidenceColor)
            }
            Row {
                TextButton(onClick = {
                    // Apply suggestion via engine tool
                    engine.sendMessage("applySuggestion", "{\"suggestion\":${suggestion.toString()},\"dryRun\":false}")
                }) { Text("Apply") }
                TextButton(onClick = {
                    // Copy to clipboard
                    engine.sendMessage("writeToClipboard", "{\"text\":\"${text}\"}")
                }) { Text("Copy") }
                TextButton(onClick = {
                    // Record dismissal feedback
                    val id = suggestion["id"]?.jsonPrimitive?.content ?: java.util.UUID.randomUUID().toString()
                    engine.sendMessage("recordSuggestionFeedback", "{\"suggestionId\":\"$id\",\"accepted\":false}")
                }) { Text("Dismiss") }
            }
        }
    }
}
