package de.Maxr1998.modernpreferences.preferences.choice

import android.content.Context
import de.Maxr1998.modernpreferences.helpers.DISABLED_RESOURCE_ID

abstract class AbstractSingleChoiceDialogPreference<T : Any>(
    key: String,
    items: List<SelectionItem<T>>,
) : AbstractChoiceDialogPreference<T>(key, items, false) {

    /**
     * The initial selection if no choice has been made and no value persisted
     * to [SharedPreferences][android.content.SharedPreferences] yet.
     *
     * Must match a [SelectionItem.key] in [items].
     */
    var initialSelection: T? = null

    var currentSelection: SelectionItem<T>? = null
        internal set

    var selectionChangeListener: OnSelectionChangeListener<T>? = null

    override fun onAttach() {
        super.onAttach()
        if (currentSelection == null) {
            resetSelection()
        }
    }

    override fun select(item: SelectionItem<T>) {
        currentSelection = item
        selectionAdapter?.notifySelectionChanged()
    }

    override fun isSelected(item: SelectionItem<T>): Boolean = item == currentSelection

    internal abstract fun saveKey(key: T)

    internal abstract fun loadKey(defaultValue: T?): T?

    override fun persistSelection() {
        currentSelection?.let { selection ->
            if (selectionChangeListener?.onSelectionChange(this, selection.key) != false) {
                saveKey(selection.key)
            }
        }
    }

    override fun resetSelection() {
        val persisted = loadKey(initialSelection)
        currentSelection = persisted?.let { items.find { item -> item.key == persisted } }
        selectionAdapter?.notifySelectionChanged()
    }

    override fun resolveSummary(context: Context): CharSequence? {
        val selection = currentSelection
        return when {
            autoGeneratedSummary && selection != null -> when {
                selection.titleRes != DISABLED_RESOURCE_ID -> context.resources.getText(selection.titleRes)
                else -> selection.title
            }
            else -> super.resolveSummary(context)
        }
    }

    fun interface OnSelectionChangeListener<T : Any> {
        /**
         * Notified when the selection of the connected [AbstractSingleChoiceDialogPreference] changes,
         * meaning after the user closes the dialog by pressing "ok".
         * This is called before the change gets persisted and can be prevented by returning false.
         *
         * @param selection the new selection
         *
         * @return true to commit the new selection to [SharedPreferences][android.content.SharedPreferences]
         */
        fun onSelectionChange(preference: AbstractSingleChoiceDialogPreference<T>, selection: T): Boolean
    }
}